add networkTest

diff --git a/Plummet b/Plummet
--- a/Plummet
+++ b/Plummet
@@ -1,5 +1,7 @@
 #! /bin/bash
 
+LOGFILE=/home/pi/p.log
+
 ARDLIB=/home/pi/arduino-1.8.10
 
 ARDTTY_PATTERN="tty(USB|ACM)"
@@ -446,7 +448,7 @@ if [ "$1" = "getMasterArd" ]; then
 fi
 
 if [ "$1" = "morningShow" ]; then
-	echo $(date) morningShow >> ~/p.log
+	echo $(date) morningShow >> $LOGFILE
 	$0 kill
 	masterArd=$($0 getMasterArd)
 	echo "Master=" $master
@@ -455,7 +457,7 @@ if [ "$1" = "morningShow" ]; then
 fi
 
 if [ "$1" = "nightShow" ]; then
-	echo $(date) nightShow >> ~/p.log
+	echo $(date) nightShow >> $LOGFILE
 	$0 kill
 	masterArd=$($0 getMasterArd)
 	echo "Master=" $master
@@ -475,4 +477,28 @@ if [ "$1" = "history" ]; then
     fi
 fi
 
+if [ "$1" = "networkTest" ]; then
+ host1=http://google.com
+ host2=http://facebook.com
+ echo -n $(date) "Checking for internet connectivity..." | tee -a $LOGFILE
+ wget -q --tries=10 --timeout=20 --spider $host1
+ if [[ $? -eq 0 ]]; then
+         echo $host1 " Online" | tee -a $LOGFILE
+   exit
+ else
+   (>&2 echo $(date) "error " $host1 " offline")
+         echo $host1 " Offline" | tee -a $LOGFILE
+ fi
+ echo -n $(date) "Checking secondary host..." | tee -a $LOGFILE
+ wget -q --tries=10 --timeout=20 --spider $host2
+ if [[ $? -eq 0 ]]; then
+   echo $host2 " Online" | tee -a $LOGFILE
+   exit
+ else
+   (>&2 echo $(date) "error " $host2 " offline")
+   echo $host2 " Offline" | tee -a $LOGFILE
+ fi
+
+
+fi
 
